### ISSUE TITLE
Android min sdk too high

### ISSUE THREAD

**Issue by ShootingKing-AM** [unalkalkan/AnkiDroid-Companion#3]
https://github.com/unalkalkan/AnkiDroid-Companion/blob/e03bf1a4853f37028f05fd740951bbb14508e907/app/build.gradle.kts#L12

The minSDK is to high, you can do down to 26 i guess. I have Android 12 and can't even install the apk.

**Comment by unalkalkan** [comment]
Heya, thanks for trying out!
Just lowered the API level down to 26, you can give it a try from this [action run](https://github.com/unalkalkan/AnkiDroid-Companion/actions/runs/7956340359)

The new APK should be at the bottom of the page

**Comment by ShootingKing-AM** [comment]
Yes it installed !

But seems like non-Basic cards are not supported?

![Screenshot_20240219-150348_AnkiDroid](https://github.com/unalkalkan/AnkiDroid-Companion/assets/4137788/d9cfae64-9210-41f2-b6fd-94e188a306fe)
![Screenshot_20240219-150341_AnkiDroid](https://github.com/unalkalkan/AnkiDroid-Companion/assets/4137788/593c54e3-18bf-4a11-8eb3-cf3928bf3d03)
![Screenshot_20240219-150326_AnkiDroid](https://github.com/unalkalkan/AnkiDroid-Companion/assets/4137788/c46312db-90fa-4d17-b788-07a11a169778)
![Screenshot_20240219-150318_AnkiDroid](https://github.com/unalkalkan/AnkiDroid-Companion/assets/4137788/983d129b-087c-4f7a-af94-ee9d40c9ef0a)
![Screenshot_20240219-150236_Chrome](https://github.com/unalkalkan/AnkiDroid-Companion/assets/4137788/2e28d214-a178-48c0-8b8f-789baf5a8968)

**Comment by zayKenyon** [comment]
Hi Android 14 user here, love this!

The README says that Android 13 & 14 are supported but the latest release 0.0.2 says 12 & 13, please could you clarify which versions are supported? 

When I tried to install v0.0.2 my system said that it was not compatible which led me here. Fortunately, this APK does install 🎉! So I suppose if the `main` SDK could be lowered then the app supports versions 12-14?

I'm not big into Android dev so apologies if I have misunderstood the SDK system. :)

**Comment by unalkalkan** [comment]
hey hey @zayKenyon, thanks for trying out! Hope it is useful for you.

> The README says that Android 13 & 14 are supported but the latest release 0.0.2 says 12 & 13, please could you clarify which versions are supported?
> When I tried to install v0.0.2 my system said that it was not compatible which led me here. Fortunately, this APK does install 🎉! So I suppose if the main SDK could be lowered then the app supports versions 12-14?

Oh yeah, that was an error on my part, I also merged these changes to main so in future anyone can get the new APK from the releases page. It should support between Android 8 (API 26) to Android 13 (API 33) now.

**Comment by unalkalkan** [comment]
> Yes it installed !

Also, thanks for trying out @ShootingKing-AM! And sorry for the late reply I'm very busy lately. 

> But seems like non-Basic cards are not supported?
> 
> Even after clicking it doesn't go anywhere or show the answer keys as shown in readme.

Yes only basic cards are supported at the moment, and yes it doesn't go away when it is in an unsupported format, as it is written in the README.

I am closing this issue but maybe you can open an issue with your screenshots, so someone with free time can lean on these problems and brainstorm on how to elegantly solve them!
